version: '3.8'



services:
  testgithubaction:
    image: jafarijason/testgithubaction_dev:${APP_VERSION}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      restart_policy:
        condition: any
      placement:
        constraints:
          # - node.role == worker
          - node.role == manager
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.testgithubaction-http.rule=Host(`${APP_DOMAIN?Variable not set}`)
        - traefik.http.routers.testgithubaction-http.entrypoints=http
        - traefik.http.routers.testgithubaction-http.middlewares=https-redirect
        - traefik.http.routers.testgithubaction-https.rule=Host(`${APP_DOMAIN?Variable not set}`)
        - traefik.http.routers.testgithubaction-https.entrypoints=https
        - traefik.http.routers.testgithubaction-https.tls=true
        - traefik.http.routers.testgithubaction-https.tls.certresolver=le
        - traefik.http.services.testgithubaction.loadbalancer.server.port=${APP_PORT}
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
    # healthcheck:
    #   test: ["CMD", "./healthCheck.sh", "${APP_PORT}"]





networks:
  traefik-public:
    external: true
